### ISSUE TITLE
[PAPER] How In-network composition can help (1.5 pages)

### ISSUE THREAD

**Issue by charif-mahmoudi** [usnistgov/NamedIoT#14]

**Comment by elmiomar** [comment]
How in-network composition can help:
• Dynamicity: dynamic and instant composition of networks  
• Self-organization/self-management/self-healing: one device died, another device will take his place
• Heterogeneity: content-based, in case of emergency response, a drone can communicate with a phone, a phone can communicate with an ambulance, an ambulance can communicate with a hospital, etc.
• Scalability: in a plug and play manner, any new device can easily be integrated into the network
• On the fly/on the go: nodes opportunistically participate in a communication with other nodes. For example, in case of the emergency response context, nodes can form a network on the fly, to communicate and make the needed resources available.
